server:
  port: 8081
spring:
  application:
    name: onlineclassroom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/bishe_classroom?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 主键生成策略
    db-config:
      id-type: ASSIGN_ID

files:
  upload:
    #    服务器路径
    path: D:/ideaproject/onlineclassroom/src/main/resources/pic/
    #    映射路径
    mapperPath: http://localhost:8081/pic/